// Migration: 0001_initial — auto-generated by makemigrations posts
// Manually created: Workaround for kent8192/reinhardt-web#3871 (makemigrations panics without Docker)
use reinhardt::prelude::*;
use reinhardt::migrations::*;

#[migration(app = "posts", dependencies = [])]
pub struct Migration0001Initial;

impl Migration for Migration0001Initial {
    fn operations(&self) -> Vec<Box<dyn MigrationOperation>> {
        vec![
            Box::new(CreateTable {
                table: "posts",
                columns: vec![
                    Column::new("id", ColumnType::BigInt).primary_key().auto_increment(),
                    Column::new("title", ColumnType::Varchar(200)).not_null(),
                    Column::new("body", ColumnType::Text).not_null(),
                    Column::new("published", ColumnType::Boolean).not_null().default("false"),
                    Column::new("created_at", ColumnType::Timestamptz).not_null(),
                ],
            }),
        ]
    }
}
