//! Repository layer for posts app
// Workaround: kent8192/reinhardt-web#3867 — repositories.rs not generated by startapp
use reinhardt::prelude::*;
use reinhardt::di::injectable_factory;
use super::models::Post;

pub struct PostRepository { pub db: DatabaseConnection }

impl PostRepository {
    // Result<T> uses reinhardt's Error alias from prelude
    pub async fn get(&self, id: i64) -> Result<Post> {
        Post::objects().get(id).all_with_db(&self.db).await?
            .into_iter().next()
            .ok_or_else(|| reinhardt::Error::NotFound("Post not found".to_string()))
    }
    pub async fn save(&self, post: &mut Post) -> Result<()> {
        Post::objects().update(post).await.map(|_| ())
    }
}

#[injectable_factory]
pub async fn post_repository(
    #[inject] db: DatabaseConnection,
) -> PostRepository {
    PostRepository { db }
}
