//! URL configuration for posts app (Pages)

use reinhardt::url_patterns;
use reinhardt::UnifiedRouter;

use crate::config::apps::InstalledApp;

// Workaround: kent8192/reinhardt-web#3869 — mode = unified requires ws_urls not generated by scaffold
#[url_patterns(InstalledApp::posts, mode = unified)]
pub fn unified_url_patterns() -> UnifiedRouter {
    UnifiedRouter::new()
}

pub fn ws_urls() -> reinhardt::WebSocketRouter {
    reinhardt::WebSocketRouter::new()
}
