//! ViewSets for posts app
// Workaround: kent8192/reinhardt-web#3867 — views.rs not generated by startapp
use reinhardt::prelude::*;
use reinhardt::views::viewsets::{FilterConfig, OrderingConfig, PaginationConfig};
use super::{models::Post, serializers::PostSerializer};

// Workaround: kent8192/reinhardt-web#3867 — #[reinhardt::viewset] macro does not exist in rc.17
pub fn viewset() -> ModelViewSet<Post, PostSerializer> {
    ModelViewSet::new("posts")
        .with_pagination(PaginationConfig::page_number(10, Some(100)))
        .with_filters(FilterConfig::new()
            .with_filterable_fields(vec!["published".to_string(), "title".to_string()]))
        .with_ordering(OrderingConfig::new()
            .with_ordering_fields(vec!["created_at".to_string(), "title".to_string()]))
}
